/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metabase

import (
	"encoding/json"
)

// checks if the Membership type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Membership{}

// Membership struct for Membership
type Membership struct {
	Id             *int32  `json:"membership_id,omitempty"`
	GroupID        *int32  `json:"group_id,omitempty"`
	UserID         *int32  `json:"user_id,omitempty"`
	IsGroupManager *bool   `json:"is_group_manager,omitempty"`
}

type Memberships map[string]Membership

// NewMembership instantiates a new Membership object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMembership() *Membership {
	this := Membership{}
	return &this
}

// NewMembershipWithDefaults instantiates a new Membership object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMembershipWithDefaults() *Membership {
	this := Membership{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Membership) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Membership) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Membership) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Membership) SetId(v int32) {
	o.Id = &v
}

// GetName returns the GroupID field value if set, zero value otherwise.
func (o *Membership) GetGroupID() int32 {
	if o == nil || IsNil(o.GroupID) {
		var ret int32
		return ret
	}
	return *o.GroupID
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Membership) GetGroupIDOk() (*int32, bool) {
	if o == nil || IsNil(o.GroupID) {
		return nil, false
	}
	return o.GroupID, true
}

// HasName returns a boolean if a field has been set.
func (o *Membership) HasGroupID() bool {
	if o != nil && !IsNil(o.GroupID) {
		return true
	}

	return false
}

// SetName gets a reference to the given int32 and assigns it to the GroupID field.
func (o *Membership) SetGroupID(v int32) {
	o.GroupID = &v
}

// GetMemberCount returns the UserID field value if set, zero value otherwise.
func (o *Membership) GetUserID() int32 {
	if o == nil || IsNil(o.UserID) {
		var ret int32
		return ret
	}
	return *o.UserID
}

// GetMemberCountOk returns a tuple with the UserID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Membership) GetUserIDOk() (*int32, bool) {
	if o == nil || IsNil(o.UserID) {
		return nil, false
	}
	return o.UserID, true
}

// HasMemberCount returns a boolean if a field has been set.
func (o *Membership) HasUserID() bool {
	if o != nil && !IsNil(o.UserID) {
		return true
	}

	return false
}

// SetMemberCount gets a reference to the given int32 and assigns it to the UserID field.
func (o *Membership) SetUserID(v int32) {
	o.UserID = &v
}

func (o Membership) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Membership) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["membership_id"] = o.Id
	}
	if !IsNil(o.GroupID) {
		toSerialize["group_id"] = o.GroupID
	}
	if !IsNil(o.UserID) {
		toSerialize["user_id"] = o.UserID
	}
	if !IsNil(o.IsGroupManager) {
		toSerialize["is_group_manager"] = o.IsGroupManager
	}
	return toSerialize, nil
}

type NullableMembership struct {
	value *Membership
	isSet bool
}

func (v NullableMembership) Get() *Membership {
	return v.value
}

func (v *NullableMembership) Set(val *Membership) {
	v.value = val
	v.isSet = true
}

func (v NullableMembership) IsSet() bool {
	return v.isSet
}

func (v *NullableMembership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMembership(val *Membership) *NullableMembership {
	return &NullableMembership{value: val, isSet: true}
}

func (v NullableMembership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMembership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
