/*
Metabase

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metabase

import (
	"encoding/json"
)

// checks if the PermissionGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionGroup{}

// PermissionGroup struct for PermissionGroup
type PermissionGroup struct {
	Id          *int32  `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	MemberCount *int32  `json:"member_count,omitempty"`
}

// NewPermissionGroup instantiates a new PermissionGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionGroup() *PermissionGroup {
	this := PermissionGroup{}
	return &this
}

// NewPermissionGroupWithDefaults instantiates a new PermissionGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionGroupWithDefaults() *PermissionGroup {
	this := PermissionGroup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PermissionGroup) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGroup) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PermissionGroup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *PermissionGroup) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PermissionGroup) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGroup) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PermissionGroup) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PermissionGroup) SetName(v string) {
	o.Name = &v
}

// GetMemberCount returns the MemberCount field value if set, zero value otherwise.
func (o *PermissionGroup) GetMemberCount() int32 {
	if o == nil || IsNil(o.MemberCount) {
		var ret int32
		return ret
	}
	return *o.MemberCount
}

// GetMemberCountOk returns a tuple with the MemberCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGroup) GetMemberCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MemberCount) {
		return nil, false
	}
	return o.MemberCount, true
}

// HasMemberCount returns a boolean if a field has been set.
func (o *PermissionGroup) HasMemberCount() bool {
	if o != nil && !IsNil(o.MemberCount) {
		return true
	}

	return false
}

// SetMemberCount gets a reference to the given int32 and assigns it to the MemberCount field.
func (o *PermissionGroup) SetMemberCount(v int32) {
	o.MemberCount = &v
}

func (o PermissionGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.MemberCount) {
		toSerialize["member_count"] = o.MemberCount
	}
	return toSerialize, nil
}

type NullablePermissionGroup struct {
	value *PermissionGroup
	isSet bool
}

func (v NullablePermissionGroup) Get() *PermissionGroup {
	return v.value
}

func (v *NullablePermissionGroup) Set(val *PermissionGroup) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionGroup) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionGroup(val *PermissionGroup) *NullablePermissionGroup {
	return &NullablePermissionGroup{value: val, isSet: true}
}

func (v NullablePermissionGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
